"""Add topology_edges

Revision ID: 0f5073f00b42
Revises: 0001_initial_schema
Create Date: 2026-09-16 01:05:21.797067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5073f00b42'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topology_edges',
    sa.Column('topology_edge_id', sa.Uuid(), nullable=False),
    sa.Column('source_junction_id', sa.String(length=64), nullable=False),
    sa.Column('target_junction_id', sa.String(length=64), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('min_travel_time_sec', sa.Float(), nullable=False),
    sa.Column('max_travel_time_sec', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('distance_meters > 0', name='ck_topology_dist_positive'),
    sa.CheckConstraint('max_travel_time_sec >= min_travel_time_sec', name='ck_topology_max_time_valid'),
    sa.CheckConstraint('min_travel_time_sec > 0', name='ck_topology_min_time_positive'),
    sa.CheckConstraint('source_junction_id != target_junction_id', name='ck_topology_no_self_loop'),
    sa.ForeignKeyConstraint(['source_junction_id'], ['junctions.junction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_junction_id'], ['junctions.junction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topology_edge_id')
    )
    op.create_index('idx_topology_source_target_active', 'topology_edges', ['source_junction_id', 'target_junction_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_topology_source_target_active', table_name='topology_edges')
    op.drop_table('topology_edges')
    # ### end Alembic commands ###
