"""add association fields to vehicle tracks

Revision ID: 81e64915d576
Revises: bfd1d8897215
Create Date: 2026-09-16 08:10:25.142584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81e64915d576'
down_revision: Union[str, Sequence[str], None] = 'bfd1d8897215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_tracks', sa.Column('association_status', sa.String(length=32), nullable=True))
    op.add_column('vehicle_tracks', sa.Column('association_confidence', sa.Float(), nullable=True))
    op.add_column('vehicle_tracks', sa.Column('association_method', sa.String(length=32), nullable=True))
    op.add_column('vehicle_tracks', sa.Column('association_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_tracks', 'association_evidence')
    op.drop_column('vehicle_tracks', 'association_method')
    op.drop_column('vehicle_tracks', 'association_confidence')
    op.drop_column('vehicle_tracks', 'association_status')
    # ### end Alembic commands ###
