"""Add appearance embedding

Revision ID: bfd1d8897215
Revises: 0f5073f00b42
Create Date: 2026-09-16 01:15:41.911991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd1d8897215'
down_revision: Union[str, Sequence[str], None] = '0f5073f00b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_tracks', sa.Column('appearance_embedding', sa.ARRAY(sa.Float()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('vehicle_tracks', sa.Column('embedding_model', sa.String(length=128), nullable=True))
    op.add_column('vehicle_tracks', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.add_column('vehicle_tracks', sa.Column('embedding_quality', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_tracks', 'embedding_quality')
    op.drop_column('vehicle_tracks', 'embedding_dimension')
    op.drop_column('vehicle_tracks', 'embedding_model')
    op.drop_column('vehicle_tracks', 'appearance_embedding')
    # ### end Alembic commands ###
