import numpy as np
from ai.contracts.models import AppearanceEmbedding

def cosine_similarity(emb_a: AppearanceEmbedding, emb_b: AppearanceEmbedding) -> float:
    """
    Computes the cosine similarity between two AppearanceEmbeddings.
    Returns a float between -1.0 and 1.0.
    """
    if emb_a.dimension != emb_b.dimension:
        raise ValueError(f"Embedding dimensions mismatch: {emb_a.dimension} != {emb_b.dimension}")
    if emb_a.model_name != emb_b.model_name:
        raise ValueError("Cannot compare embeddings generated by different models.")

    v_a = np.array(emb_a.vector, dtype=np.float32)
    v_b = np.array(emb_b.vector, dtype=np.float32)
    
    norm_a = np.linalg.norm(v_a)
    norm_b = np.linalg.norm(v_b)

    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0

    return float(np.dot(v_a, v_b) / (norm_a * norm_b))
